/**
 * This is the type of the data that will be passed to the function.    
 */
export interface LLMToSQLResponse {
    /**
     * The SQL query generated by the LLM model.
     */
    sqlQuery: string;
    /**
     * If the SQL query was executed, the results of the query by sequelize.
     */
    results?: any[];
}

/**
 * This is the data  todo
 */