import { 
    OpenAIConfig as LLMAPIConfig, 
    ModelConfig as LLMAPIModelConfig 
} from 'llm-api'

import { 
    Options as SequelizeOptions 
} from 'sequelize';

/**
 * This is the type of the data that will be passed to the function.    
 */
export interface LLMToSQLResponse {
    /**
     * The SQL query generated by the LLM model.
     */
    sqlQuery: string;
    /**
     * If the SQL query was executed, the results of the query by sequelize.
     */
    results?: any[];
}

/**
 * This is the information needed to init a llm-api instance.
 */
export type { LLMAPIConfig };

/**
 * This is the information needed to init a llm-api instance.
 */
export type { LLMAPIModelConfig };

/**
 * This is the information needed to init a sequelize instance.
 */
export type { SequelizeOptions };